### PR TITLE
added another Recursion Tester file

### PR DESCRIPTION
**Pull request by musabdullah0**
all the other testers are outdated, suduko solver is no longer part of the assignment.

### CODE REVIEW

**Comment by taylorkline** [comment]
I made this repo 5 years ago lol. I wouldn't be surprised if it's outdated. How did you even find it?

**Comment by musabdullah0** [comment]
Idk who found it, but a bunch of ppl started using ur tester files and
passing the repo around. It’s been hella helpful bc Scott says sharing test
files is allowed but barely anyone posts theirs on piazza. Nobody made any
pull requests over the past 5 years?

**Comment by taylorkline** [comment]
Yep, you're the first.

**Comment by musabdullah0** [comment]
well, you the goat for making this repo. have a nice day, sir.

**Pull request merged**
